#sets and set function  in python
# set()
# add()
# pop() 
# remove()
# clear()
# discard()
l=[10,20,30,40,50]
print("converting list to set:")
s=set(l)
print(s)
print("removing 20 from the set:")
s.remove(20)
print(s)
print("adding 60 to the set:")
s.add(60)
print(s)
print("poping element from set:")
s.pop()
s.pop()
print(s)
a=[1,2,3]
print("update element in set:")
s.update(a)
print(s)
